In [1]:
import numpy as np

In [2]:
numbers = [1,2,3,4,5,6,7,8,9,10]

In [10]:
numbers_np = np.array(numbers)
print(numbers)
print(numbers_np)
numbers
numbers_np

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# list of three lists
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
# this is a unclear representation of the 2d lists
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# for clear 2d represatation of the 2d lists
list_of_lists_np = np.array(list_of_lists)
list_of_lists_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# creating a list with numpy using numpy arange
np.arange(1,11)
# here the two params are start and end+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# we can also add another param to numpy arange
np.arange(1,11,2)
# here the third param is the step size

array([1, 3, 5, 7, 9])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,10,5)
# here the first param is the start of the range
# the second param is the end of the range
# the third param is the number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
#indentity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
#random numbers
np.random.rand(5)
#this generates 5 random numbers between 0 and 1


array([0.64702228, 0.82063562, 0.50796928, 0.22527478, 0.22650578])

In [ ]:
np.random.rand(3,3) #for 2d matrix

array([[0.8286194 , 0.8667363 , 0.49559742],
       [0.91479339, 0.18484414, 0.12705602],
       [0.81697649, 0.85581454, 0.09373051]])

In [ ]:
np.random.randn(10) #this generates 3 random numbers from a normal distribution

array([ 0.74620082,  0.12843559,  0.81479828, -1.21612807,  0.6335617 ,
        0.83778895,  1.31841757, -0.45008385,  0.61949413, -1.75257897])

In [ ]:
np.random.randn(3,3) #for 2d matrix

array([[ 0.44966089, -0.31639292,  1.69179048],
       [-1.05413894, -0.69813331,  1.29221561],
       [-1.35154995,  0.68293519, -0.41990477]])

In [24]:

np.random.randint(1,100,10) #this generates 10 random numbers between 1 and 100-1

array([ 2, 83, 49, 16, 33, 87, 36, 99, 75, 88], dtype=int32)

In [25]:
np_random_int = np.random.randint(1,100,20)

In [26]:
# reshaping the array
np_random_int.reshape(4,5)

array([[80, 96, 96, 59, 19],
       [72, 11, 66,  9, 93],
       [45, 40, 10, 80, 52],
       [93, 94, 17, 64, 16]], dtype=int32)

In [28]:
#finding max
np.max(np_random_int)
#or
np_random_int.max()

np.int32(96)

In [29]:
#finding min
np.min(np_random_int)
#or
np_random_int.min()

np.int32(9)

In [30]:

#index of max
np.argmax(np_random_int)
#or
np_random_int.argmax()

np.int64(1)

In [31]:

#index of min
np.argmin(np_random_int)
#or
np_random_int.argmin()

np.int64(8)

In [32]:
#shape of array
np_random_int.shape

(20,)

In [33]:
#reshaping and then chekcing shape
new_np_random_int = np_random_int.reshape(5,4)
new_np_random_int.shape

(5, 4)

In [34]:

#checking datatype
np_random_int.dtype

dtype('int32')

In [35]:
#importing randint function from numpy
from numpy.random import randint

In [36]:

#generating 10 random numbers between 1 and 100
randint(1,100,10)

array([ 4, 35, 33, 81, 81, 63, 65,  6, 26, 13], dtype=int32)

In [37]:
#array of 0 to 10
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
#value of index 8
arr[8]

np.int64(8)

In [39]:
#list of items from 1 to 5
arr[1:6]

array([1, 2, 3, 4, 5])

In [40]:
#everything to index 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [41]:

#evrything from index 6 to end
arr[6:]

array([ 6,  7,  8,  9, 10])

In [42]:

#setting index 0 to 5 to 100
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
#make another array from 0 to 20
arr2 = np.arange(0,21)
# 0 to 10 in another variable
arr3 = arr2[:10]
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#changing the value of arr3 from index 0 to 5 into 99
arr3[:5] = 99
arr3


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [46]:
arr2

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [47]:

#resetting the arr2 variable
arr2 = np.arange(0,21)
# copy a part of arr2 into arr3
arr3 = arr2[:10].copy()
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr3[:5] = 99
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [49]:

print(arr2)
#arr2 is not changed but arr3 is changed
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99 99 99 99 99  5  6  7  8  9]


In [50]:
#making a 2d array
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [51]:
#there are two ways to grab a value from a 2d array
print(arr2d[0,1])
#single brackets with a comma
print(arr2d[0][1])
#double brackets

10
10


In [52]:
#we can also slice the 2d array with single brackets
print(arr2d[0:2,1:3])
#and also with double brackets
print(arr2d[0:2,1:3])

[[10 15]
 [25 30]]
[[10 15]
 [25 30]]


In [53]:
#but to simplify we can grab the first 2 row
print(arr2d[0:2])

[[ 5 10 15]
 [20 25 30]]


In [54]:

#to grab the last 2 row
print(arr2d[1:])

[[20 25 30]
 [35 40 45]]


In [56]:
#to grab the first 2 rows and first 2 columns
print(arr2d[0:2,0:2])
#with double brackets
print(arr2d[0:2][0:2])

[[ 5 10]
 [20 25]]
[[ 5 10 15]
 [20 25 30]]


In [ ]:
#  to grab the first row and last 2 columns
print(arr2d[0:1,2:])

[[15]]


In [58]:
# create a new array from 1 to 20
arr = np.arange(1,21)
# find all the elements less then 5 
arr[arr<5]

array([1, 2, 3, 4])

In [59]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [60]:
arr[arr<5]

array([1, 2, 3, 4])

In [61]:
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [62]:
#now reshaping the array
arr = arr.reshape(5,10)

arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [63]:
# create a new array from 0 to 10
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
#addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
#substraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
# multiplication
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [67]:
print(arr + 100)
print(arr - 100)
print(arr * 100)

[100 101 102 103 104 105 106 107 108 109 110]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[   0  100  200  300  400  500  600  700  800  900 1000]


In [68]:
# dividing 0 by 1
0/1

0.0

In [69]:
# we get an error
arr/arr

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12752\1748444562.py:2: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [70]:
#expomnent
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [71]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [72]:
#exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [73]:
#sin
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [74]:
#log
np.log(arr)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12752\2388929641.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])